### ISSUE TITLE
Solution to pvw not populating

### ISSUE THREAD

**Issue by ndsizeif** [allyring/pvw#8]
Nice project

Some of the reported errors running the app are likely due to issues with the
latest releases of lsof. I initally had trouble running pvw but noticed that I
was running the most recent version of lsof (4.98). After trying an older
release, pvw ran fine.

Running on Linux:

- lsof 4.94 or newer did not populate for me, and caused crashes with certain flags.
the 4.94 release seemed to have introduced [significant changes](https://github.com/lsof-org/lsof/releases)
- lsof 4.93 worked like a... charm

An update to the Readme may steer other users to a solution if their package
manager ends up installing a newer, problematic version of lsof.

**Comment by allyring** [comment]
Thanks for letting me know about this, and I'm glad you like the project! I'll update the readme now, and I'll see if I can implement a solution to using the newer version soon.

Although, it might be better to see if I could implement the scans that `lsof` does in Go, to remove it as a dependency; I'll definitely need to do some man page digging to make that work though, so it might take a while.

(also, the pun - intentional or not - was very much appreciated :wink:)

**Comment by allyring** [comment]
I've just pushed a new build, v1.4.0, which should make pvw use the latest version of lsof. Thanks for the heads up on this!
